### ISSUE TITLE
写真を投稿すると表示されない

### ISSUE THREAD

**Issue by SHIN747** [SHIN747/my-first-blog2#10]
リンクエラーになる
![スクリーンショット 2023-12-18 130621](https://github.com/SHIN747/my-first-blog2/assets/78301484/0f534a10-edda-4d24-b083-dca1e32b6370)

**Comment by SHIN747** [comment]
めちゃくちゃ便利やん
これ、githubすごいわ

**Comment by saku-shirakura** [comment]
解決したら、closeを押しておいてください。
